repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: fix-encoding-pragma
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.17
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.6
    hooks:
      - id: insert-license
        files: \.py$
        args: ['--license-filepath', 'devtools/license-header']
