dist: xenial

language: python

cache: pip

python:
  - 3.6
  - 3.7
  - 3.8-dev

env:
  - PIPENV_VERBOSITY=-1

install:
  - pip install --upgrade pip
  - pip install -U pipenv
  - pipenv install --dev

script:
  - pipenv run python -m pytest --cov=parselglossy tests/ --doctest-modules
  - pipenv run python -m pytest --flake8 parselglossy
  - pipenv run python -m pytest --black parselglossy
  - pipenv run python -m pytest --mypy parselglossy

after_success:
  - pipenv run codecov

# Generated 2019-03-29 by @robertodr with `travis setup pypi`
deploy:
  provider: pypi
  user: robertodr
  password:
    secure: tr8AIL+qAVtZW8XgXZ4Thadh5qcBUVXo3D8C4LXiEFt4qT2N04NhPOEPxITAkat2N7mwKTfkK1CUPgo68KF7lyVsXBUWsZ8EdjqX7vOk4UzbCvGr28sTT55kJa2GMFoCjV92LUFXyapUc05GJzlMHLhp+mg6LW7rv6kSkCjdHnTbP+e7WknpQ5eoVYMWa+SEwqiODqVG7bhHnmQoKydX33PTYZ4l0U11mV/aNvLqw789METJvEZ22wpd786MHOLMW2Bv8qpRl4T44qWpQIoGdYiqJoTJGIHoA+gB3LeI0ar+/oN+mDhGUEcuEpOMhbNunAeiHg1u7ayxDcs4BXrO4jRE8ZNskp/HwIxReawzVLSqg99fhwW9dzIj3bNUyeLyjxlaMuTo5dSVDslFpzVhmS6W4yU6ir59xDWycayrZwy+iXjDU8cdG83H1kgGpf5UePJKttIlGMftskcNBHJs79a0VzNBGSVyUttrrnRTNpIAnM1XGXpbI3aBUWtsR06o1gG6M++sYrHemNSxKXqKuIGmxhQKkKOFZ0DjgY/A7vMDXnjFpr6CXVFxzg7HeJBtrSQAXGq4OtnPAqWTY22N4CGE/olEht/ToT2DlOsz49x65xg+jUsSWZB9FrV2JnXN6sMCGcI2JXFrkFRPGTqhiPzSwvRYBHZiMpyp1a7mjXI=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: dev-cafe/parselglossy
    python: 3.6
