dist: xenial

language: python

python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8-dev

env:
  - PIPENV_VERBOSITY=-1

install:
  - pip install --upgrade pip
  - pip install -U pipenv
  - pipenv install --dev -e .

script:
  - pipenv run py.test --cov=parselglossy tests/ --doctest-module
  - pipenv run py.test --flake8 parselglossy
  - pipenv run py.test --mypy parselglossy

after_success:
  - pipenv run codecov

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: robertodr
  password:
    secure: VD8VF1Q/gD/cfAQzeUrxv6JKfXvFWlfrzu2JtprVj+Bxb/Twf2136p7nndtUqrgqvTXo2iaJ+ZMCB27hXG0SJl++KsgYzImBF4tQKfFGGBIb8KuahTbeMHp2Z4KwLiSKs0ZI1PC05g384ukEKGXrk5cENngR+vMcAkajcNBkS95q1SbVG1pxe7U7R5cBGS6YZPk+OUH80vsV7uDYrcF7dR/HoVJtpEnGDSQitEXz0bW0hHUnPtsfhTcNoVpfApe4HY8OigedOhKv6CIZJ6gvqnsBBh5Zk3mOW0c63BdpmvInGBJUxCt+yN/DVwIU9+s+BSKpcLIP3t2K5a8MxYhVbcQfogNSqWEs2faSl+Zgc4ZZTsMhsDBIpiId966hWYMgU8xFA7WaFHoVSnn/Dr2bucq46yFqVivkvPL+WYLJUBK39kiNB0P34w451swvU6psaT1pwpUN9gLhLLN7Bux3a5KdcRdXAC+mUijSNnUjVbN4E/VYq2be87UMutYGlQJ/dDmrtOMlaxR0MMmkR6+GEJpi/V6cYjCuKnvMv5TOfnjfRjtZRhKk4aegZFscYYAerJs0qBTzOzEHbKYv1ImSMwFJ0DuDiQ9BJ0h157nR0jDEgpK0+6qHxTtdkyK3eFNny1gsFW8IZbgRpkTFnsp37vfB+jVZHnhRVaFpcIP9VdY=
  on:
    tags: true
    repo: dev-cafe/parselglossy
    python: 3.6
