dist: xenial

language: python

python:
  - 3.6
  - 3.7
  - 3.8-dev

env:
  - PIPENV_VERBOSITY=-1

install:
  - pip install --upgrade pip
  - pip install -U pipenv
  - pipenv install --dev -e .

script:
  - pipenv run py.test --cov=parselglossy tests/ --doctest-module
  - pipenv run py.test --flake8 parselglossy
  - pipenv run py.test --mypy parselglossy

after_success:
  - pipenv run codecov

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: robertodr
  password:
    secure: LUsU73OFhrXoQMDNbTk1+rLsmB7Y1WefWRkoNdjQ8MyNWUzBXSximHmuVTZ2RKSldOGOQD6eqwxesft4QsvUXndQKRdR6Px22N2EMnuVvRA8PUJp2OUOZ1JDyaetWst6WhdlIRpdVgSJYu6BaWt8pTNZQVFD7k8FLxW1GMzKnKwryEc9lQaHtQhADd/dGCCmHZ2+gF3Wd9Yo7AfL/JpTmGKF88jslquWM8im+oUmcXMkVYEqiJXit7WSjJie79bjEFrFCowmz00A6mx7yOb1JGMeHa2cRXbJrV9FPC0rmipAa4DDSzhjIHMtY3ukanoeFYDD7ylNQdcahFNXhLzA+/f0EOrXUY09Lbs5tXwGYQsWtYhpoDTHHiMxeJEsvo7ImdV782NZW5hqvB+J3CrBg3hmJYUHlJRGbGILU8rwcj+pQ16+q0qG8KSKGbwdx2QOiE161DRVpcm/olVf3ff9L/KRqImvlZ3oEosjlFjZUSj+rg2JPNKllOQp5oNxl5UGkKpep7wSgQS6jvoISf66wMkstZnRXi0uA8oO+sImLRAfskMdjviiYdUcptpeG3YV1pFq99YuSj2Q5L31Ea7X5DhqHtKcfuSGbjnV4AE3A7ZA+lkxmQ0w0xctEoXIpqNH3ZP9YMFiEKYE9qDhEN83veUAe2zn8OPUj5bMz9khMQY=
  on:
    tags: true
    repo: dev-cafe/parselglossy
    python: 3.6
