name: Test parselglossy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types:
      - created

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip flit
        flit install --symlink --extras=dev,test --deps=production
    - name: Test with pytest
      run: |
        python -m pytest --cov=parselglossy --cov-report=xml --doctest-modules tests/
        python -m pytest --flake8 parselglossy
        python -m pytest --black parselglossy
        python -m pytest --mypy parselglossy
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
