name: Test parselglossy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types:
      - created

jobs:
  build:
    env:
      HYPOTHESIS_PROFILE: "ci"

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9, "3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip flit
          flit install --symlink --extras=dev,test --deps=production

      - name: Test with pytest
        run: |
          python -m pytest --cov=parselglossy --cov-report=xml --doctest-modules tests/

      - name: Flake8 lints
        run: |
          python -m flake8 parselglossy

      - name: Black lints
        run: |
          python -m black --check parselglossy

      - name: Mypy lints
        run: |
          python -m mypy parselglossy

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
